### ISSUE TITLE
Downloading the SD card is broken

### ISSUE THREAD

**Issue by Noodlez1232** [Birdthulu/FPM-Installer#1]
When downloading the SD card, Mediafire tries to "repair" the download and the curl ends up downloading a php page instead of the file which is intended.

**Comment by jsj1027** [comment]
Try it again rn, an update was going on.

**Comment by jsj1027** [comment]
Let me know if it's still broken

**Comment by Noodlez1232** [comment]
Still broken. This is the error I get:
```
Downloading sd card
#=#=-  #      #                                                                                                                                                                               
Extracting sd card

gzip: stdin: not in gzip format
```

**Comment by Noodlez1232** [comment]
Upon `cat`ing out the output, once again, it's just a webpage.

**Comment by jsj1027** [comment]
Looking into this now. Currently not seeing why this is happening. But probably linked to mediafire

**Comment by SilverMight** [comment]
Also experiencing the same issue here.

**Comment by Noodlez1232** [comment]
I think a possible solution is to put the SD card .gz into the repo and update the repo each time a new SD card update comes out, although 1GB is kinda large.

**Comment by jsj1027** [comment]
You have to pay github for repos over 1gb the sd cards even zipped are 1.6GB

**Comment by jsj1027** [comment]
Im also not seeing the gzip issue.
Are @NateDogg1232 @SilverMight you using hosted versions of the script? Or running the command?

**Comment by Noodlez1232** [comment]
I am using hosted versions of the script, but even when I run the curl command myself, it returns a new webpage.

I believe Mediafire generates a new download link for each IP. So since my IP is different, it tries to generate a new download link for me.

**Comment by jsj1027** [comment]
The script has been updated many times since you opened this issue, please use the new script. The mediafire link has changed

**Comment by jsj1027** [comment]
Does it work using the newest script instead of the hosted version?

**Comment by Noodlez1232** [comment]
It is compiling right now, I should've just tested the curl command it had in it.

**Comment by Noodlez1232** [comment]
Yeah, it is still not working.

**Comment by Noodlez1232** [comment]
Even with the newest script.

**Comment by SilverMight** [comment]
Can confirm, still getting the same issue.

**Comment by jsj1027** [comment]
Just posted a patch, can you confirm if the new version works @NateDogg1232 @SilverMight?

**Comment by jsj1027** [comment]
It wasnt just a link change so you'll need the new script

**Comment by Noodlez1232** [comment]
Testing it now

**Comment by Noodlez1232** [comment]
It's not done downloading, but I'm going to say, given its 1.6G file size that it is now downloading the correct file.

**Comment by jsj1027** [comment]
SICKKK.

Please let me know if anything else goes wrong. Im keeping this issue open till I can get 1-2 confirms that this is fixed.

**Comment by Noodlez1232** [comment]
Confirmed working

**Comment by jsj1027** [comment]
@NateDogg1232 Thank you
@SilverMight How about for you?

**Comment by jsj1027** [comment]
Confirmed working by multiple people on discord. Closing for now. Will re open if issues pop up.
