### ISSUE TITLE
Ubuntu MATE 20.04 Install Script Issue

### ISSUE THREAD

**Issue by AlexArdelean** [Birdthulu/FPM-Installer#15]
Patching tarball...
Patching DiscExtractor.h
sh: 231: [: Illegal number: 
Skipping patch for Arch based distros
Patching wxWidgets3 for Ubuntu 20.04 based distros
Adding FPP config files...
cmaking...
CMake Warning (dev) at CMakeLists.txt:10 (set):
  implicitly converting 'string' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Detected architecture: x86_64
-- Performing Test FLAG_C_HAVE_SSE2
-- Performing Test FLAG_C_HAVE_SSE2 - Success
-- Performing Test FLAG_CXX_HAVE_SSE2
-- Performing Test FLAG_CXX_HAVE_SSE2 - Success
-- Performing Test FLAG_C_HAVE_WALL
-- Performing Test FLAG_C_HAVE_WALL - Success
-- Performing Test FLAG_CXX_HAVE_WALL
-- Performing Test FLAG_CXX_HAVE_WALL - Success
-- Performing Test FLAG_C_TYPE_LIMITS
-- Performing Test FLAG_C_TYPE_LIMITS - Success
-- Performing Test FLAG_CXX_TYPE_LIMITS
-- Performing Test FLAG_CXX_TYPE_LIMITS - Success
-- Performing Test FLAG_C_SIGN_COMPARE
-- Performing Test FLAG_C_SIGN_COMPARE - Success
-- Performing Test FLAG_CXX_SIGN_COMPARE
-- Performing Test FLAG_CXX_SIGN_COMPARE - Success
-- Performing Test FLAG_C_IGNORED_QUALIFIERS
-- Performing Test FLAG_C_IGNORED_QUALIFIERS - Success
-- Performing Test FLAG_CXX_IGNORED_QUALIFIERS
-- Performing Test FLAG_CXX_IGNORED_QUALIFIERS - Success
-- Performing Test FLAG_C_UNINITIALIZED
-- Performing Test FLAG_C_UNINITIALIZED - Success
-- Performing Test FLAG_CXX_UNINITIALIZED
-- Performing Test FLAG_CXX_UNINITIALIZED - Success
-- Performing Test FLAG_C_LOGICAL_OP
-- Performing Test FLAG_C_LOGICAL_OP - Success
-- Performing Test FLAG_CXX_LOGICAL_OP
-- Performing Test FLAG_CXX_LOGICAL_OP - Success
-- Performing Test FLAG_C_SHADOW
-- Performing Test FLAG_C_SHADOW - Success
-- Performing Test FLAG_CXX_SHADOW
-- Performing Test FLAG_CXX_SHADOW - Success
-- Performing Test FLAG_C_INIT_SELF
-- Performing Test FLAG_C_INIT_SELF - Success
-- Performing Test FLAG_CXX_INIT_SELF
-- Performing Test FLAG_CXX_INIT_SELF - Success
-- Performing Test FLAG_C_MISSING_DECLARATIONS
-- Performing Test FLAG_C_MISSING_DECLARATIONS - Success
-- Performing Test FLAG_CXX_MISSING_DECLARATIONS
-- Performing Test FLAG_CXX_MISSING_DECLARATIONS - Success
-- Performing Test FLAG_C_MISSING_VARIABLE_DECLARATIONS
-- Performing Test FLAG_C_MISSING_VARIABLE_DECLARATIONS - Failed
-- Performing Test FLAG_CXX_MISSING_VARIABLE_DECLARATIONS
-- Performing Test FLAG_CXX_MISSING_VARIABLE_DECLARATIONS - Failed
-- Performing Test FLAG_C_NO_STRICT_ALIASING
-- Performing Test FLAG_C_NO_STRICT_ALIASING - Success
-- Performing Test FLAG_CXX_NO_STRICT_ALIASING
-- Performing Test FLAG_CXX_NO_STRICT_ALIASING - Success
-- Performing Test FLAG_C_NO_EXCEPTIONS
-- Performing Test FLAG_C_NO_EXCEPTIONS - Success
-- Performing Test FLAG_CXX_NO_EXCEPTIONS
-- Performing Test FLAG_CXX_NO_EXCEPTIONS - Success
-- Performing Test FLAG_C_VISIBILITY_INLINES_HIDDEN
-- Performing Test FLAG_C_VISIBILITY_INLINES_HIDDEN - Failed
-- Performing Test FLAG_CXX_VISIBILITY_INLINES_HIDDEN
-- Performing Test FLAG_CXX_VISIBILITY_INLINES_HIDDEN - Success
-- Performing Test FLAG_C_VISIBILITY_HIDDEN
-- Performing Test FLAG_C_VISIBILITY_HIDDEN - Success
-- Performing Test FLAG_CXX_VISIBILITY_HIDDEN
-- Performing Test FLAG_CXX_VISIBILITY_HIDDEN - Success
-- Performing Test FLAG_C_FOMIT_FRAME_POINTER
-- Performing Test FLAG_C_FOMIT_FRAME_POINTER - Success
-- Performing Test FLAG_CXX_FOMIT_FRAME_POINTER
-- Performing Test FLAG_CXX_FOMIT_FRAME_POINTER - Success
-- Performing Test FLAG_C_GGDB
-- Performing Test FLAG_C_GGDB - Success
-- Performing Test FLAG_CXX_GGDB
-- Performing Test FLAG_CXX_GGDB - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- X11 support enabled
-- Xrandr not found
-- Checking for module 'xi>=1.5.0'
--   Found xi, version 1.7.10
-- Could NOT find FFmpeg (missing: FFmpeg_INCLUDE_avcodec FFmpeg_LIBRARY_avcodec FFmpeg_INCLUDE_avformat FFmpeg_LIBRARY_avformat FFmpeg_INCLUDE_avutil FFmpeg_LIBRARY_avutil FFmpeg_INCLUDE_swscale FFmpeg_LIBRARY_swscale avcodec avformat avutil swscale) 
-- libav/ffmpeg not found, disabling AVI frame dumps
-- Could NOT find LIBUDEV (missing: LIBUDEV_LIBRARY LIBUDEV_INCLUDE_DIR) 
-- Could NOT find libevdev (missing: LIBEVDEV_LIBRARY LIBEVDEV_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:505 (message):
  Couldn't find libevdev and/or libudev.  Can't build evdev controller
  backend.

  Disable ENABLE_EVDEV if you wish to build without controller support

[CMakeError.log](https://github.com/Birdthulu/FPM-Installer/files/5184875/CMakeError.log)
[CMakeOutput.log](https://github.com/Birdthulu/FPM-Installer/files/5184876/CMakeOutput.log)

**Comment by AlexArdelean** [comment]
At first it said I was missing xi so I downloaded it. I also followed instructions on readme.

**Comment by Sukid** [comment]
Did Ubuntu Mate switch to primarily using Snap packages like mainline ubuntu did? If so you might not actually have the libudev and libevdev that it's looking for. It's not super likely but it's possible. try sudo apt-get libudev-dev and sudo apt-get libevdev-dev and see what happens.

**Comment by AlexArdelean** [comment]
> 
> 
> Did Ubuntu Mate switch to primarily using Snap packages like mainline ubuntu did? If so you might not actually have the libudev and libevdev that it's looking for. It's not super likely but it's possible. try sudo apt-get libudev-dev and sudo apt-get libevdev-dev and see what happens.

I figured out I had to add more dependencies. They're all located in the discord.
