### ISSUE TITLE
New 2.2 Won't Compile in Arch-based Linux

### ISSUE THREAD

**Issue by ThisNekoGuy** [Birdthulu/FPM-Installer#17]
[CMakeOutput.log](https://github.com/Birdthulu/FPM-Installer/files/5833464/CMakeOutput.log)
[CMakeError.log](https://github.com/Birdthulu/FPM-Installer/files/5833465/CMakeError.log)

I'm having trouble with the compilation part of the script...

**Comment by MininuxDev** [comment]
I have the same problem on arch, however I could run it with ChrisHobday's Appimage (#18)

**Comment by jsj1027** [comment]
Please use the appimage that Chris created for now.
We are working on an official solution, see my respond in Appimage thread.

**Comment by TheGreatestJannet** [comment]
I would like to mention that I'm on Arch and it compiled correctly. The Paths don't work though. Manually changing them fixes it though.
