### ISSUE TITLE
Received error during compilation in Manjaro

### ISSUE THREAD

**Issue by HombreLaser** [Birdthulu/FPM-Installer#7]
Received this same error during compilation:
https://github.com/FasterMelee/FasterMelee-installer/issues/50

Tried the fix in soundtouch header file. Didn't work.

**Comment by jsj1027** [comment]
Is this still an issue on the current version, P+v2.15?

**Comment by HombreLaser** [comment]
> Is this still an issue on the current version, P+v2.15?

No, now it compiles as is, even with GCC 10. I'll close the issue.
